### ISSUE TITLE
The tick marks are not shown on the checkboxes after adding an applet to the basket on the basket page

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1025]
**Steps to reproduce:**
1. Log in to the Library https://library-staging.mindlogger.org/ (snakessqa@gmail.com // 123456)
2. Mark the checkboxes on applets and add them to the basket
3. Navigate to the basket
4. Look at the result

**Actual result:** The tick marks are not shown on the checkboxes after adding an applet to the basket on the basket page
**Video**:https://www.screencast.com/t/huumdFNqED
**Expected result:** The tick marks are shown on the checkboxes after adding an applet to the basket on the basket page. checkboxes should be checked

**Environment:**
https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 90.0.4430.212)

**Comment by natalia-muzyka** [comment]
The issue is fixed **for basket** but broken on the main page
https://www.screencast.com/t/9BFFqIDL

On the main library page tick marks currently have the next behavior after clicking the checkbox for the first time:
- highest level: if it is the first selecting of the applet then the loader icon is shown near the checkbox and checkbox isn't marked
- expanded applet: after the second clicking the checkbox the tick mark is displayed but the second level (activity) isn't displayed as marked
- expanded to the item level: after clicking directly on the item the higher levels are not marked with "-"

Video:
https://www.screencast.com/t/TPUWjrb6

Environment:
https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 91.0.4472.77 )

**Comment by natalia-muzyka** [comment]
The issue is fixed
https://www.screencast.com/t/IJeD1Qnsx

Environment:
https://library-staging.mindlogger.org/ (Win 10 // Chrome Version 91)
