### ISSUE TITLE
Scheduling an activity for one time completion doesn't work

### ISSUE THREAD

**Issue by hotavocado** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1211]
Currently affects: 
HBN EMA
RnB EMA

Why: The prequestionnaire activity is meant to be only completed once, but because one-time-completion isn't working, we leave it unscheduled. It doesn't go away after the user fills it out, takes up space and is distracting in the user's activity page on their phone. 

Tested 8/30/21 at 4:12pm v0.17.12

Current behavior:
After scheduling an activity for one time completion and completing the activity on my phone, the activity remains visible.

Expected behavior:
the activity disappears after completion 

![Screen Shot 2021-08-30 at 4 18 59 PM](https://user-images.githubusercontent.com/24463939/131399962-0c00403d-f54e-40fb-8b84-c7644d624b36.png)

**Comment by hotavocado** [comment]
thx @jj105!

**Comment by natalia-muzyka** [comment]
Verified as fixed

Video: https://www.screencast.com/t/I5uVyqHI

https://admin-staging.mindlogger.org/
Win 10 // Chrome 93.0.4577.63 
ML v0.17.24 (staging)
iPhone SE (2020) // iOS 14.2	
Samsung Galaxy S7 SM-G930FD // Android 8.0
maddison_ml@protonmail.com // qwertyuio
avani_ml@protonmail.com // 12345678
applet: applet 1

**Comment by natalia-muzyka** [comment]
The issue is reproducible again for DBT applet.
Not reproducible for NIMH.

taking activity: https://www.screencast.com/t/rpcwIvljO
scheduling + csv report + data tab: https://www.screencast.com/t/gTa1oEmXdh4

https://admin-staging.mindlogger.org/
Win 10 // Chrome 
ML v0.18.16 (staging)
iPhone 8 Plus // iOS 13.3
Samsung Galaxy S7 SM-G930FD // Android 8.0

owner: josephine_ml@protonmail.com qwertyui
users:
qatl.customer@protonmail.com 3FuuFz60
qatl.customer1@protonmail.com 3FuuFz61
applet: DBT (1)
Applet password: Qwe123!!!

**Comment by natalia-muzyka** [comment]
verified as fixed: https://www.screencast.com/t/iWLMOmz1M

https://admin-staging.mindlogger.org/
Win 10 // Chrome 96.0.4664.110 
ML v0.18.21 (staging)
iPhone 8 Plus // iOS 13.3
Samsung Galaxy S7 SM-G930FD // Android 8.0
owner: josephine_ml@protonmail.com qwertyui
applet: DBT (1), DBT, NIMH
Applet password: Qwe123!!!
