### ISSUE TITLE
Unable to edit Applet

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1244]
Steps to recreate 
1. Login with wavanauken/ abcd123 
2. Switch to 007 account 
3. Try to edit one of the Robin applets 
4. See results 

Expected: The user is shown the applet builder 
Actual: The edit button is greyed out

**Comment by natalia-muzyka** [comment]
I'm not able to reproduce this issue with my prod accounts:
geria.test@gmail.com	// 123456
geria2.test@gmail.com	// McgzF127

@WorldImpex could you provide an email for your account, please, so I can test this ticket?

**Comment by WorldImpex** [comment]
This issue is fixed

**Comment by natalia-muzyka** [comment]
The issue is reproducible. Before the "Edit" button was greyed out I edited the applet (copied, edited, deleted activities)

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/c72cf572-6ae4-49d4-a777-f8fe88455d11)

Environment:
https://admin-staging.mindlogger.org/
jeraka1732@wodeda.com	1234567890
mix applet (jeraka)
Applet password	Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/FWhZIoj4l

Environment:
https://admin-staging.mindlogger.org/
jeraka1732@wodeda.com 1234567890
mix applet (jeraka)
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
The issue is reproduced ON STAGING again after adding and then deleting the A/B trails activity from the applet.

Video: https://www.screencast.com/t/sSvaK4s8Wqq

Environment:
https://admin-staging.mindlogger.org/
jeraka1732@wodeda.com 1234567890
combined report
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/C1iVx5JMfyUj

Environment:
https://admin-staging.mindlogger.org/
jeraka1732@wodeda.com 1234567890
combined report
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
The issue is reproduced on the particular applet:

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/7caad973-0eb3-441b-9988-20e6ecc29a46)

https://admin-staging.mindlogger.org/
Win 10 // Chrome 100.0.4896.127
jeraka1732@wodeda.com	1234567890
combined report (2)
Applet password	Qwe123!!!

**Comment by natalia-muzyka** [comment]
@jj105  Reproduces after editing and log out/log in: 

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/436ba6d5-5e75-406e-98ae-a036534456f1)

https://admin-staging.mindlogger.org/
Win 10 // Chrome 100.0.4896.127
jeraka1732@wodeda.com 1234567890
combined report (2)
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/a9ihajVOJ

https://admin-staging.mindlogger.org/
Win 10 // Chrome 100.0.4896.127
jeraka1732@wodeda.com 1234567890
combined report (2)
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
@jj105 The issue reproduces after editing another applet on the different account:

https://www.screencast.com/t/J0vjnqmw

https://admin-staging.mindlogger.org/
Win 10 // Chrome 100.0.4896.127
kimberly_ml@protonmail.com	12345678
conditionals (kimberly)
Applet password Qwe123!!!

**Comment by natalia-muzyka** [comment]
Unable to reproduce this issue. Close the ticket.

**Comment by natalia-muzyka** [comment]
The issue is reproducible after adding and then deleting cognitive activities.
The "Edit" button is greyed out. Although there is an ability to open a builder via "Build/Edit an applet" button, the error pop-up is shown up after an attempt to save the changes.
Notes: Reproucible on the applet's duplicate as well.

Video: https://www.screencast.com/t/eorBgy5pdZv

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 101
ml_general_acc@protonmail.com	12345678
cognitive tasks, cognitive tasks duplicate
Applet password	Qwe123!!!

**Comment by natalia-muzyka** [comment]
Reminder to retest after deployment: 
reproduces in the duplicated applet with CST touch activity as well.
https://www.screencast.com/t/0AgfL9bhSMeT

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 101
qwe123@qwe123.qwe123	qwe123
My own CST 2 (1)

**Comment by natalia-muzyka** [comment]
@jj105 the issue is fixed for:
ml_general_acc@protonmail.com 12345678
cognitive tasks, cognitive tasks duplicate

but still reproducible for:
qwe123@qwe123.qwe123 qwe123
My own CST 2 (1)

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/ngoGIbhU57

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 101
qwe123@qwe123.qwe123 qwe123
My own CST 2 (1)
