### ISSUE TITLE
[bug] can accept ownership with the wrong account

### ISSUE THREAD

**Issue by lioneldeveauxcri** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1338]
Anirudh transfered ownership to an applet to the mindlogger-admin@cri-paris.org
When I received the link, I accidentally accepted it with my lionel.deveaux@cri-paris.org mindlogger account
I was able to accept it, and ownership was transferred to my personal account, which shouldn't have happened. There needs to be one extra layer of security here (checking who is connected)

**Comment by WorldImpex** [comment]
Hey Lionel! This is not a bug but a feature. We do not want to railroad the transfer of the ownership of an applet, since most organizations will be use something like admin@cri-paris.com or whatever for an owner account. We can still send the ownership to a trusted individual's email address (lionel@cri-paris.com) and that person can add it to whatever account from there
