### ISSUE TITLE
[PROD] Ped Screener exports a blank report

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1374]
Steps to recreate
1. Log into admin
2. Navigate to the data visualization 
3. View report 
4. See results 

Expected: The user's report is shown with text
Actual: The report is blank per attached 
[https://app.zenhub.com/files/189080374/ae5bfaf1-d1fb-4875-9c4a-2e3d7e522b24/download](https://app.zenhub.com/files/189080374/ae5bfaf1-d1fb-4875-9c4a-2e3d7e522b24/download)

**Comment by natalia-muzyka** [comment]
@devbtech 
I've experienced today the same issue on staging: 
blank PDF report is downloaded on admin panel: https://www.screencast.com/t/d9lBpVpMH

I found that I had a comma in the cumulative title in one of the activities and thought maybe this caused issues, so I removed the comma but it didn't help (as previously symbol "/" caused issue on prod for PedScreener applet). Slash issue was found and fixed by @jj105 

for the same activity, webapp summary report(page) is empty and pdf report is missing user score info. and this webapp activity stays In progress after completing it: https://www.screencast.com/t/JOf30NqOyucb

account: 
kimberly_ml@protonmail.com	// 12345678
applet: splash screen test 1
activity: (don't complete) PC 200x200 gif

**Comment by natalia-muzyka** [comment]
@devbtech here is a new applet with a reproducible issue (on staging):
josephine_ml@protonmail.com	qwertyui
mix applet / mix activity (pdf)
Applet password	Qwe123!!!

If it helps: I created mix activity (pdf) with copying from the first one(mix activity) and added a cumulative item with two cumulative rules.

**Comment by natalia-muzyka** [comment]
still reproducible on production: https://www.screencast.com/t/e1IlxPFQ
I use demo@mindlogger.org	abcd123 (PedScreener applet)

**Comment by natalia-muzyka** [comment]
verified as fixed:
https://www.screencast.com/t/Ab7IoBNoCHMX

https://admin.mindlogger.org/
Win 10 // Chrome 96.0.4664.110
