### ISSUE TITLE
Token Cart is not shown on Account 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1411]
Last Friday 1/7 I recorded negative behaviors and today I cannot see the tokens dashboard on admin for the below account. I can see it on other applets that do not have balances recorded 

account:
bernard_ml@protonmail.com // qwe123!!!
applet: TL refresh test
Applet password: Qwe123!!!

**Comment by techdev137** [comment]
tokens from negative behaviors are not available because there is issue in the content of applet

![image.png](https://images.zenhubusercontent.com/5fbce3e9259bafeab239c8c3/c2a1f9d0-04e4-4abb-b408-4074470d4c35)

( start/end times are empty and rate of increase are 0)
I think we need to either delete applet or fix content of it.

**Comment by natalia-muzyka** [comment]
I edited the content of the applet and DataViz Frequency/Token chart is shown now:
https://www.screencast.com/t/A8J4Pz2Pa
