### ISSUE TITLE
Allow Coordinator to Schedule Activity Flows

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1552]
As an editor, I want to schedule an activity flow so that I can show the right content to the user at the right time. 

Requirements 
-  On a general or individual schedule, activity flows should be available to schedule 
- Activity flow items should come after the activities in an applet with the activity flow icon visible 
- Setting up an activity flow's schedule is the same as an activity. 
- If an activity-specific customization is required (timer, idle timer, repeats, etc) then the setting is placed on all activities in that flow 
- If a notification is set, then the notification shows the Activity flow's name in the message and only sends 1 notification at the specified time. 
- On mobile, the activity flow should function as a regular activity and contain the scheduling messaging  
- If an activity or activity flow has been hidden in the applet builder then when creating a scheduled event for one show the scheduling module with Hidden turned on 
   - If the coordinator hides an activity, then it should be hidden in the applet builder 

![Blank diagram.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/495c6592-2088-4b17-9820-cac05983322e)

[Additional Designs](https://www.figma.com/file/VYuZ9vFaPfK6JnXeAXG8wW/Pre-SRC-Features?node-id=29%3A145229)

[Design](https://www.figma.com/file/VYuZ9vFaPfK6JnXeAXG8wW/Pre-SRC-Features?node-id=29%3A145229)

**Comment by natalia-muzyka** [comment]
Issues:

Blocker:
Fixed - Activity flow name is changed in the calendar after the activities within the flow / the flow was hidden #1766
Fixed - The flow looks always available in the app after saving the schedule #2813
Closed - The activity is not hidden on the mobile app/website after activating the "Hidden" toggle on the Calendar #1767**

?waiting for clarification from Arno and Benett: New (after #2813) :
**The interrupted("in progress") flow is continued instead of restarting in the next repeated period**
https://mindlogger.atlassian.net/browse/MIN-44
**The interrupted ("in progress") flow is not hidden after the scheduled end activity time**
https://mindlogger.atlassian.net/browse/MIN-45

Highest:
Fixed - App crashes after idle time is left in the flow activity #2807
Fixed - Timer is not shown up in the flow activity#2808

High:
Closed - Hidden activity/flow is not shown up in the scheduled start time #2835
