### ISSUE TITLE
It is possible to create and save event with "Notifications" turned ON and not specified notification time

### ISSUE THREAD

**Issue by natalia-muzyka** [ChildMindInstitute/mindlogger-admin-OLD-Vue#1685]
**Preconditions**
The user is logged in on the admin panel
https://admin-staging.mindlogger.org/

**Steps to reproduce**

1. Open a site https://admin-staging.mindlogger.org/
2. Click the "View users" button on any applet
3. Open general or individual calendar
4. Add a new event
5. Turn ON Notifications, but do not specify the time
6. Click "Save" to save the event
7. Click "Save" to save the schedule
8. Observe the result

**Actual result**
It is possible to create and save event with "Notifications" turned ON and not specified notification time

**Expected result**
There should be a warning/error after clicking "Save" on the event card

**Video:** https://www.screencast.com/t/fqlxYzLpW1H

**Environment:**
https://admin-staging.mindlogger.org/
v0.17.8
Win 10 / Chrome 102
jeligi9407@zneep.com 123456
applet: test conditional (1)

**Comment by natalia-muzyka** [comment]
Verified as fixed: https://www.screencast.com/t/s0wNnFJwI

Environment:
https://admin-staging.mindlogger.org/
v0.17.11
Win 10 / Chrome 103

**Comment by MaksimYurys** [comment]
@devbtech @Matchdev120 I can create and save event with "Notifications" turned ON and not specified notification time. Probably the issue started reproducing after the latest changes due to the 1751 ticket:
https://app.zenhub.com/workspaces/mindlogger-webapp-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/1751

Video: https://images.zenhubusercontent.com/189080374/abd196d1-79d1-4707-810b-556247c84616/4bcab6be_268f_49cf_b6fd_74015d370ffc.mp4

Environment:
https://admin-staging.mindlogger.org/
v0.17.18
Win 10 / Chrome 103

**Comment by eleonova-scn** [comment]
Reproduced on September 22, 2022.

**Comment by natalia-muzyka** [comment]
Verified as fixed: 

![image.png](https://images.zenhubusercontent.com/60ab57c8916945b978a3da92/bd89d5a3-8cea-4f27-b10b-d7f74b9a07e4)

Environment:
https://admin-staging.mindlogger.org/
v0.18.0
Win 10 / Chrome 105
BigSur / Chrome 105
