### ISSUE TITLE
Wrong API link is set just after logout admin panel

### ISSUE THREAD

**Issue by devbtech** [ChildMindInstitute/mindlogger-admin-OLD-Vue#199]

**Comment by sergeysemenuta** [comment]
The issue is fixed.
 The correct API link is set  after logging out from the  admin panel "https://api-staging.mindlogger.org/api/v1"
![2020-06-05_12-18-13.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/83673adc-3323-47be-9888-4542e19670e6)
Checked on the site https://admin-dev.mindlogger.org/
Environment:
Win 10 //Chrome Version 83.0.4103.97
