### ISSUE TITLE
Remove all events from production account 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#281]
Clear on admin page clears all events that have been scheduled for an applet 

![mindlogger-admin.png](https://images.zenhubusercontent.com/5e1336f1b24025a7b2654475/96c2b1b0-bf3b-4ea9-889d-23e2524753e0)

**Comment by WorldImpex** [comment]
works as expected

**Comment by sergeysemenuta** [comment]
Clearing the events from general calendar clears the events from individual calendar
https://www.screencast.com/t/xfMH3qybOu
Expected result: Clearing the events from general calendar don't clear the events from individual calendar
Note: The issue is reproducible on staging as well https://admin-staging.mindlogger.org/
Reproduced on:
https://admin.mindlogger.org/
Win10//Chrome 84

**Comment by devbtech** [comment]
Deploying to staging first. @Matchdev120 is going to make a PR to production as well then we can deploy changes to production.

**Comment by sergeysemenuta** [comment]
Clearing the events from the general calendar doesn't remove events on the individual calendar

-  It is not possible to clear all events from the individual calendar for the user
Video: https://www.screencast.com/t/hTXdcjt23
**To recreate:**
1. Schedule events on the general calendar
2. Set an individual schedule for user A
3. Click the "CLEAR" button on the individual calendar and click "YES"
4. Look at the result

https://admin-staging.mindlogger.org/
Win  10// Chrome 88

**Comment by Matchdev120** [comment]
@sergeysemenuta 
The Pull request is not merged yet. Please check it again after deploying the Pr.
https://github.com/ChildMindInstitute/mindlogger-admin/pull/817

**Comment by sergeysemenuta** [comment]
The issue is fixed.
https://admin-staging.mindlogger.org/
Win 10// Chrome 88
