### ISSUE TITLE
Fix the timezone in the dashboard

### ISSUE THREAD

**Issue by ngonzalvez** [ChildMindInstitute/mindlogger-admin-OLD-Vue#347]
User responses created today (Sep 14) are shown as if they were created yesterday (Sep 13) in the dashboard due to the timezone. The dashboard should show the dates correctly.

![image](https://user-images.githubusercontent.com/1501339/93129895-1d9d2d00-f6a8-11ea-9306-2d708ac8d959.png)

**Comment by sergeysemenuta** [comment]
The current date is not showing up in the chart
![2020-09-16_11-51-18.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/62fc4b2b-5876-4936-a54c-ee6c3d6664f6)
That happens because of the wrong order of the days. It shows - 8/17,  8/19 ,8/21, 8/23 . Expected: 8/17 , 8/19, 8/20, 8/21, 8/22 etc
Environment:
https://admin-staging.mindlogger.org/
Win10//Chrome 85

**Comment by sergeysemenuta** [comment]
The original issue is fixed. The dashboard shows the dates correctly.
The current date is displayed in the chart
![2020-09-21_13-28-03.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/3dd1658d-f6cc-4239-b75b-5a1388c81221)
**Environment:**
https://admin-staging.mindlogger.org/
Win10//Chrome 85
