### ISSUE TITLE
Test notifications/ scheduling for newly created applets 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#368]
We want to make sure notifications and scheduling works for newly created applets on the builder

**Comment by sergeysemenuta** [comment]
Checked General and individual scheduling/notifications for duplicated applets. Works as expected.
Currently not able to check for the newly created applets via the applet builder because of the issue [371](https://app.zenhub.com/workspaces/mindlogger-5e11094d0c26311588da9626/issues/childmindinstitute/mindlogger-admin/371)

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome Version 85
MindLogger app v 0.13.17
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3

**Comment by sergeysemenuta** [comment]
Checked the General/Individual scheduling with notifications for the applet created via applet builder
Works as expected

Environment:
https://admin-staging.mindlogger.org/
Win 10 // Chrome Version 85
MindLogger app v 0.13.23
Samsung Galaxy S10 // Android 9
iPhone X // iOS 13.3
