### ISSUE TITLE
The applet is not created via applet builder after submitting the password of the applet

### ISSUE THREAD

**Issue by sergeysemenuta** [ChildMindInstitute/mindlogger-admin-OLD-Vue#387]
**Steps to reproduce:**
1. Log in to the admin panel https://admin-staging.mindlogger.org/ (owen@ml.com // 123456)
2. Navigate to the applet builder
3. Specify the applet name and description
4. Add activity and items to the activity and save
5. Click the "EXPORT SCHEMA" button
6. Enter the applet password and submit it
7. Pay attention to the result

**Actual result:** The applet is not created via applet builder after submitting the password of the applet
**Video:** https://www.screencast.com/t/bKeXlxGJFZ
**Expected result:** The applet is created via applet builder after submitting the password of the applet. The "Upload Received" pop-up is displayed and the applet is uploaded to the admin panel

**Environment:**
https://admin-staging.mindlogger.org/
Win 10 //Chrome 85

**Comment by sergeysemenuta** [comment]
Currently, it works as an Edit functionality 
After creating the applet via applet builder and clicking the "EXPORT SCHEMA" button the following message is displayed "Your applet is successfully updated" 
Video: https://www.screencast.com/t/Bq5o2kickjP
Expected result: The applet is building. We will send you an email in 10 mins or less when it has been successfully created or failed.

Checked on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 85

**Comment by WorldImpex** [comment]
@jj105 First question: since we are uploading from the builder, can the upload not fail so we are only showing the success message? Second question: Can we have different messages for: 
1. When an applet is edited show "Your applet is successfully updated." 
2. When an applet is newly created "Your applet is successfully uploaded."

**Comment by jj105** [comment]
@WorldImpex @sergeysemenuta 
1. yes, I think we can show only success message. ( if editor enters something wrong, then we can show alert before editor clicks "save to dashboard" button because we are managing applet builder code and workflow. )
2. yes, we can show different messages for edit applet and create applet.

**Comment by WorldImpex** [comment]
@jj105 Could you update this using this ticket?

**Comment by sergeysemenuta** [comment]
The issue is fixed.
https://www.screencast.com/t/MqNDUSuWi9O1
Checked on:
https://admin-staging.mindlogger.org/
Win 10 // Chrome 85
