### ISSUE TITLE
[PROD] When creating an applet with a radio button, exported response data shows as NULL 

### ISSUE THREAD

**Issue by WorldImpex** [ChildMindInstitute/mindlogger-admin-OLD-Vue#543]
Steps to create: 
1. In production log into wavanauken+2@gmail.com/ abcd123 
2. Take assessment called radio button 
3. Go to admin and export that user's data. 
4. See results

Expected: The selection the user made is displayed 
Actual: The word NULL is shown. It looks like if there is more then one option that the 2nd, 3rd, etc record the correct numerical value 

[Export ](https://docs.google.com/spreadsheets/d/18z25rVoPFPU6ZiKFEEs-eRSBKQ0w1g-c3aDrhwezfMA/edit?usp=sharing)

**Comment by sergeysemenuta** [comment]
Rechecked on staging/production servers. The issue is reproducible for radio items on the HIMH applet
![2020-12-01_11-39-04.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/cd84efb8-8c9c-42ee-8ac1-93214294270d)
Works as expected for applets created via the applet builder

![2020-12-01_12-30-05.png](https://images.zenhubusercontent.com/5e59389dceb759b87367c8cb/4818df4e-4b0f-4786-a3e7-3f09cc4e4768)
